[project]
name = "spotsync"
version = "3.0.0"
description = "A extension of SpotDL to create and sync Spotify playlists"
readme = "README.md"
authors = [
    { name = "Rikiub", email = "rikiub.dev@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "spotdl>=4.2.0",
    "rich>=13.4.2"
]

[project.scripts]
spotsync = "spotsync:run_cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
